# Generated by Django 6.0.4 on 2026-04-30 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_product_category"),
        ("stores", "0006_alter_store_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="stores.store",
            ),
            preserve_default=False,
        ),
    ]
