# Generated by Django 6.0.4 on 2026-05-01 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_store"),
        ("stores", "0006_alter_store_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="stores.store",
            ),
        ),
    ]
