# Generated by Django 6.0.4 on 2026-04-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("customer", "Customer"), ("merchant", "Merchant")],
                default="customer",
                max_length=20,
            ),
        ),
    ]
