# Generated by Django 6.0.4 on 2026-04-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_merchant",
            field=models.BooleanField(default=False),
        ),
    ]
