# Generated by Django 6.0.4 on 2026-04-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_rename_stores_store"),
    ]

    operations = []
