# Generated by Django 6.0.4 on 2026-04-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_auto_20260430_0842"),
    ]

    operations = []
