# Generated by Django 6.0.4 on 2026-04-30 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0004_auto_20260430_0849"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
