# Generated by Django 6.0.4 on 2026-04-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0005_store_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
